<?php
namespace FuriosoJack\MasterModelsAWS\Tests;

use Orchestra\Testbench\BrowserKit\TestCase as TestFather;

/**
 * Class TestCase
 * @author Juan Diaz - FuriosoJack <iam@furiosojack.com>
 */
class TestCase extends TestFather
{

    public function getPackageProviders($app)
    {
        return [

        ];
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }



}
